[package]
name = "photon-gpui"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[features]
default = ["engine"]
engine = []

[dependencies]
gpuix-native = { path = "../../vendor/gpuix/packages/native", default-features = false }
gpui_platform = { path = "../../vendor/gpuix/zed/crates/gpui_platform", default-features = false, features = ["runtime_shaders"] }
gpui = { path = "../../vendor/gpuix/zed/crates/gpui", default-features = false, features = ["font-kit", "profiler"] }
serde_json = "1"

[build-dependencies]
cc = "1"
