[workspace]
resolver = "2"
members = [
    "crates/photon-cli",
    "crates/photon-core",
    "crates/photon-ffi",
    "crates/photon-app",
    "crates/photon-shell",
    "crates/photon-presentation-broker",
    "crates/photon-presentation-ipc",
    "crates/photon-omnibox",
    "crates/photon-shortcuts",
]
exclude = ["Engine/Libraries/LibJS/Flap", "vendor/gpui-ce"]

[workspace.package]
edition = "2024"
license = "BSD-2-Clause"
version = "0.1.0"
