[workspace]
resolver = "2"
members = [
    "crates/photon-cli",
    "crates/photon-core",
    "crates/photon-gpui",
    "crates/photon-native-addon",
    "crates/photon-omnibox",
]
exclude = ["Engine/Libraries/LibJS/Flap", "vendor/gpuix"]

[workspace.package]
edition = "2024"
license = "BSD-2-Clause"
version = "0.1.0"
