
[[icon]]
name = "minimize"
provider = "lucide"
path = "lucide/minimize.svg"
license = "ISC"
source = "https://github.com/lucide-icons/lucide/tree/main/icons/minus.svg"

[[icon]]
name = "close"
provider = "lucide"
path = "lucide/close.svg"
license = "ISC"
source = "https://github.com/lucide-icons/lucide/tree/main/icons/x.svg"

[[icon]]
name = "restore"
provider = "lucide"
path = "lucide/restore.svg"
license = "ISC"
source = "https://github.com/lucide-icons/lucide/tree/main/icons/minimize-2.svg"


[[icon]]
name = "maximize"
provider = "lucide"
path = "lucide/maximize.svg"
license = "ISC"
source = "https://github.com/lucide-icons/lucide/tree/main/icons/square.svg"

[[icon]]
name = "back"
provider = "lucide"
path = "lucide/back.svg"
license = "ISC"
source = "https://github.com/lucide-icons/lucide/tree/main/icons/arrow-left.svg"

[[icon]]
name = "forward"
provider = "lucide"
path = "lucide/forward.svg"
license = "ISC"
source = "https://github.com/lucide-icons/lucide/tree/main/icons/arrow-right.svg"

[[icon]]
name = "reload"
provider = "lucide"
path = "lucide/reload.svg"
license = "ISC"
source = "https://github.com/lucide-icons/lucide/tree/main/icons/rotate-cw.svg"
